#ifndef _IEVENTCONST_H_
#define _IEVENTCONST_H_

#define	 EVENTID_CREATE_VIDEO_SESSION_SUCCESS				1
#define	 EVENTID_CREATE_AUDIO_SESSION_SUCCESS				2
#define	 EVENTID_CREATE_VIDEO_SESSION_FAILED				3
#define	 EVENTID_CREATE_AUDIO_SESSION_FAILED				4
#define	 EVNETID_VIDEO_SESSION_CLOSEED_SUCCESS				5
#define	 EVENTID_AUDIO_SESSION_CLOSEED_SUCCESS				6

#define	 EVENTID_LOGIN_USENAME_WRONG						7
#define	 EVENTID_LOGIN_PASSWORD_WRONG						8
#define	 EVENTID_LOGIN_USER_REPEATED						16
#define	 EVENTID_LOGIN_USER_LOCKED							17

#define	 EVENTID_RECEIVE_VIDEO_ERROR						9
#define	 EVENTID_RECEIVE_AUDIO_ERROR						10
#define	 EVENTID_DEVICE_NOT_SUPPORT_VIDEO					11
#define	 EVENTID_DEVICE_NOT_SUPPORT_AUDIO					12

#define  EVENTID_DEVICE_NO_PRIVILEGE						13
#define  EVENTID_DEVICE_MAX_CONNECTION						14

#define	 EVENTID_FILE_PLAYBACK_END							15

#endif
