#ifndef _PLAYSTATUS_H_
#define _PLAYSTATUS_H_

class PlayStatus
{
public:
	enum
	{
		PLAY_STATUS_STOP = 1,       //停止
		PLAY_STATUS_PAUSE = 2,		//暂停
		PLAY_STATUS_PLAY = 3,		//播放
		PLAY_STATUS_FASTPLAY = 4,	//快进
		PLAY_STATUS_SLOWPLAY = 5,	//慢放
		PLAY_STATUS_FRAME_PLAY = 6, //帧进
		PLAY_STATUS_FRAME_BACK = 7,  //帧退
		PLAY_STATUS_2X_SLOWPLAY = 8,	//2倍慢放
		PLAY_STATUS_4X_SLOWPLAY = 9,	//4倍慢放
		PLAY_STATUS_8X_SLOWPLAY = 10,	//8倍慢放
		PLAY_STATUS_16X_SLOWPLAY = 11,	//16倍慢放
		PLAY_STATUS_2X_FASTPLAY = 13,	//2倍快放
		PLAY_STATUS_4X_FASTPLAY = 14,	//4倍快放
		PLAY_STATUS_8X_FASTPLAY = 15,	//8倍快放
		PLAY_STATUS_16X_FASTPLAY = 16,	//16倍快放
		PLAY_STATUS_FASTBACK = 12,	//快退
		PLAY_STATUS_2X_FASTBACK = 17,	//快退2倍
		PLAY_STATUS_4X_FASTBACK = 18,	//快退4倍
		PLAY_STATUS_8X_FASTBACK = 19,	//快退8倍
		PLAY_STATUS_16X_FASTBACK = 20	//快退16倍
	} ;
};

#endif //_PLAYSTATUS_H_

