
#define PT_PAN_SPEED_LEN 2
#define PT_TILT_SPEED_LEN 2
#define PT_PAN_POSION_LEN 4
#define PT_TILT_POSION_LEN 4

#define SENOR_ZOOM_LEN 2

#define PTZ_S2_COMMAND_LEN  64
#define PTZ_S2_PT_COMMAND_LEN 13
#define PTZ_S2_PT_COMMON_COMMAND_LEN 9
#define PTZ_S2_PT_STRIP_COMMAND_LEN 21
#define PTZ_S2_PT_VERTICAL_MAX_COMMAND_LEN 12
