#ifndef _SN_DOMAIN_CONST_H_
#define _SN_DOMAIN_CONST_H_

/************************************************************************
实体类ID
************************************************************************/

enum DOMAIN_ID
{
	DOMAIN_ID_NULL              			= 0,

	//报警 1-40
	DOMAIN_ID_ALARM_ACTION       			= 1,
	DOMAIN_ID_ALARM_DATA         			= 2, 
	DOMAIN_ID_ALARM_EVENT       			= 3,
	DOMAIN_ID_ALARM_EXTYPE        			= 4,
	DOMAIN_ID_ALARM_IN_DEVICE       		= 5,
	DOMAIN_ID_ALARM_IN_DEVICE_INFO       	= 6, 
	DOMAIN_ID_ALARM_INFO       				= 7,
	DOMAIN_ID_ALARM_INFO_EX        			= 8,
	DOMAIN_ID_ALARM_INFO_EX_QUERY_PARAM  	= 9,
	DOMAIN_ID_ALARM_INFO_EX_RECORD_SET  	= 10,
	DOMAIN_ID_ALARM_IN_STATISTIC        	= 11, 
	DOMAIN_ID_ALARM_IO_EVENT       			= 12,
	DOMAIN_ID_ALARM_LOG_QUERY_PARAM      	= 13,
	DOMAIN_ID_ALARM_LOG_RECORD_SET      	= 14,
	DOMAIN_ID_ALARM_OUT_ACTION         		= 15, 
	DOMAIN_ID_ALARM_OUT_DEVICE       		= 16,
	DOMAIN_ID_ALARM_OUT_STATISTIC       	= 17,
	DOMAIN_ID_ALARM_OVERLAY_ACTION       	= 18,
	DOMAIN_ID_ALARM_PARAM       	  		= 19,
	DOMAIN_ID_ALARM_PTZ_ACTION        		= 20, 
	DOMAIN_ID_ALARM_PTZ_ACTION_EX       	= 21,
	DOMAIN_ID_ALARM_RECORD_ACTION        	= 22,
	DOMAIN_ID_ALARM_RECORD_POLICY        	= 23, 
	DOMAIN_ID_ALARM_SERVICE_PARAM       	= 24,
	DOMAIN_ID_ALARM_SNAPSHOT_POLICY      	= 25,
	DOMAIN_ID_ALARM_TYPE        			= 26,
	DOMAIN_ID_ALARM_VALID_LEVEL       		= 27,
	DOMAIN_ID_CONFIG_CHANGE_FLAG			= 28,
	DOMAIN_ID_IVA_CAMERA_TAMPER_PARAM		= 29,
	DOMAIN_ID_IVA_INTRUSION_PARAM			= 30,
	DOMAIN_ID_IVA_LINE_COUNTING_PARAM		= 31,
	DOMAIN_ID_ALARM_OUT_DEVICE_INFO			= 32,
	DOMAIN_ID_CAMERA_PARAM					= 33,
	
	//FILE 41-45
	DOMAIN_ID_FILE_SYSTEM					= 41,
	DOMAIN_ID_FILE_SYSTEM_ABILITY			= 42,

	//面积  46-55
	DOMAIN_ID_AREA_PARAM       				= 46,
	DOMAIN_ID_AREA_PARAM_V2       			= 47,

	//音频 56-70
	DOMAIN_ID_AUDIO_ABILITY					= 56,
	DOMAIN_ID_AUDIO_DECODE_TYPE      		= 57,
	DOMAIN_ID_AUDIO_ENCODE_QUALITY       	= 58,
	DOMAIN_ID_AUDIO_ENCODE_TYPE       		= 59,
	DOMAIN_ID_AUDIO_EX_ABILITY        		= 60, 
	DOMAIN_ID_AUDIO_INFO       				= 61,
	DOMAIN_ID_AUDIO_IN_TYPE        			= 62,
	DOMAIN_ID_AUDIO_OUT_TYPE				= 63,
	//视频 71-85
	DOMAIN_ID_AV_DATA						= 71,
	DOMAIN_ID_AV_DATA_EX      				= 72,
	DOMAIN_ID_AV_DATA_QUEUE       			= 73,
	DOMAIN_ID_AV_DATA_STRUCT       			= 74,
	DOMAIN_ID_AV_FRAME_DATA        			= 75, 
	DOMAIN_ID_AV_STREAM_ABILITY       		= 76,
	DOMAIN_ID_AV_STREAM_ATTRIBUTE_ABILITY	= 77,
	DOMAIN_ID_AV_STREAM_MULTICAST_ADDR		= 78,
	DOMAIN_ID_AV_STREAM_PARAM				= 79,

	//COM 86-90
	DOMAIN_ID_COM_DATA						= 86,

	//通讯 90-95
	DOMAIN_ID_COMMUNICATION_PARAM    		= 90,
	DOMAIN_ID_COMMUNICATION_SECURITY_PARAM 	= 91,


	//隐私遮蔽 96-105
	DOMAIN_ID_BLIND_ABILITY					= 96,
	DOMAIN_ID_BLIND_ABILITY_CONFIGURE   	= 97,
	DOMAIN_ID_BLIND_ABILITY_V2       		= 98,
	DOMAIN_ID_BLIND_AREA_INFO_V2       		= 99,
	DOMAIN_ID_BLIND_AREA_PARAM        		= 100, 
	DOMAIN_ID_BLIND_AREA_PARAMV2			= 101,

	//摄像机 106-120
	DOMAIN_ID_CAMERA_ABILITY				= 106,
	DOMAIN_ID_CAMERA_CONFIGURE_EX    		= 107,
	DOMAIN_ID_CAMERA_DEVICE       			= 108,
	DOMAIN_ID_CAMERA_EX_ABILITY       		= 109,
	DOMAIN_ID_CAMERA_GROUP        			= 110, 
	DOMAIN_ID_CAMERA_GROUP_RELATION      	= 111,
	DOMAIN_ID_CAMERA_INFO       			= 112,
	DOMAIN_ID_CAMERA_MASK_EVENT       		= 113,


	//CMS  121-140
	DOMAIN_ID_CMS_CAMERA_REGISTER_INFO_PARAM	= 121,
	DOMAIN_ID_CMS_DEVICE_REGISTER_INFO_PARAM    = 122,
	DOMAIN_ID_CMS_EXTERN_CONFIG_PARAM       	= 123,
	DOMAIN_ID_CMS_EXTERN_CONFIG_PARAM_V2       	= 124,
	DOMAIN_ID_CMS_PROTOCOL_PARAM        		= 125, 
	DOMAIN_ID_CMS_REGISTER_INFO_PARAM      		= 126,
	DOMAIN_ID_CMS_REGISTER_PARAM       			= 127,
	DOMAIN_ID_CMS_REGISTER_SERVER_PARAM       	= 128,
	DOMAIN_ID_CMS_REGISTER_SERVER_PARAM_V2      = 129,
	DOMAIN_ID_CMS_STREAM_PARAM       			= 130,

	//CYCLE 141-150
	DOMAIN_ID_CYCLE_CAMERA_GROUP_RELATION       = 141,
	DOMAIN_ID_CYCLE_GROUP      					= 142,
	DOMAIN_ID_CYCLE_PICTURE_PARAM       		= 143,

	//DDNS 151-160
	DOMAIN_ID_DDNS_PARAM       					= 151,
	DOMAIN_ID_DDNS_PARAM_V2      				= 152,
	DOMAIN_ID_DDNS_PROVIDER       				= 153,
	DOMAIN_ID_DDNS_SUNELL_PARAM       			= 154,

	//DETECTION 160-165
	DOMAIN_ID_DETECTION_AREA       				= 161,
	DOMAIN_ID_DETECTION_AREA_V2      			= 162,

	//DEVICE 166-196
	DOMAIN_ID_DEVICE_ABILITY					= 166,
	DOMAIN_ID_DEVICE_ACCESS_PARAM    			= 167,
	DOMAIN_ID_DEVICE_AVSTREAM_PARAM       		= 168,
	DOMAIN_ID_DEVICE_BASE_INFO       			= 169,
	DOMAIN_ID_DEVICE_DATE_TIME        			= 170, 
	DOMAIN_ID_DEVICE_EX_ABILITY      			= 171,
	DOMAIN_ID_DEVICE_IMAGE_FORMAT      			= 172,
	DOMAIN_ID_DEVICE_MCU_INFO       			= 173,
	DOMAIN_ID_DEVICE_NODE_INFO      			= 174,
	DOMAIN_ID_DEVICE_OSD_INFO       			= 175,
	DOMAIN_ID_DEVICE_PARAM						= 176,
	DOMAIN_ID_DEVICE_PORT    					= 177,
	DOMAIN_ID_DEVICE_PRODUCT_INFO       		= 178,
	DOMAIN_ID_DEVICE_RECORD_STAT_REPORT      	= 179,
	DOMAIN_ID_DEVICE_ROI_INFO_PARAM        		= 180, 
	DOMAIN_ID_DEVICE_SEARCH_PARAM     			= 181,
	DOMAIN_ID_DEVICE_SECURITY_PARAM      		= 182,
	DOMAIN_ID_DEVICE_SERVICE_PARAM       		= 183,
	DOMAIN_ID_DEVICE_SUMMARY_INFO      			= 184,
	DOMAIN_ID_DEVICE_TYPE      					= 185,
	DOMAIN_ID_DEVICE_VIDEO_ENCODE_QUALITY		= 186,
	DOMAIN_ID_DEVICE_WORK_STATE    				= 187,
	DOMAIN_ID_DEVICE_INFO						= 188,
	DOMAIN_ID_DEVICE_INFO_EX					= 189,

	//DISK 197- 205
	DOMAIN_ID_DISK_ALARM_PARAM      			= 197,
	DOMAIN_ID_DISK_ALARM_PARAM_V2      			= 198,
	DOMAIN_ID_DISK_ATTRIBUTE_EX     			= 199,
	DOMAIN_ID_DISK_STATISTIC					= 200,

	//I3G 206-215
	DOMAIN_ID_I3G_MESSAGE_CONNECT_POLICY_PARAM  = 206,
	DOMAIN_ID_I3G_ABILITY_PARAM      			= 207,
	DOMAIN_ID_I3G_NETWORK_PARAM    				= 208,
	DOMAIN_ID_I3G_POLICY_PARAM					= 209,
	DOMAIN_ID_I3G_STATE_PARAM   				= 210,
	DOMAIN_ID_I3G_TIME_CONNECT_POLICY_PARAM		= 211,

	//IRPOWER 216-220
	DOMAIN_ID_IR_POWER_ITEM   				= 216,
	DOMAIN_ID_IR_POWER_PARAM_V2				= 217,

	//LANGUAGE 221-225
	DOMAIN_ID_LANGUAGE_ABILITY   			= 221,
	DOMAIN_ID_LANGUAGE_TYPE					= 222,

	//LAYOUT 226-235
	DOMAIN_ID_LAYOUT_ABILITY  				= 226,
	DOMAIN_ID_LAYOUT_DECODING_ABILITY      	= 227,
	DOMAIN_ID_LAYOUT_MODEL   				= 228,
	DOMAIN_ID_LAYOUT_WINDOW					= 229,
	DOMAIN_ID_LAYOUT_WND_INFO  				= 230,
	DOMAIN_ID_LIVE_VIDEO_LAYOUT  			= 231,
	DOMAIN_ID_PLAY_LAYOUT  					= 232,
	DOMAIN_ID_LIVE_VIDEO_CHANNEL			= 233,
	//LOGIN 236-240
	DOMAIN_ID_LOGIN_FAILED_USER  			= 236,
	DOMAIN_ID_LOGIN_SESSION  				= 237,

	//LOG 241-260
	DOMAIN_ID_LOG_INFO  					= 241,
	DOMAIN_ID_LOG_INFO_EX  					= 242,
	DOMAIN_ID_LOG_REQUEST_PARAM 			= 243,
	DOMAIN_ID_LOG_REQUEST_PARAM_EX  		= 244,


	//MCU 261-265
	DOMAIN_ID_MCU_INFO						= 261,
	DOMAIN_ID_MCU_SELF_CHECK_PARAM 			= 262,
	DOMAIN_ID_PT_CHECK_PARAM 				= 263,
	DOMAIN_ID_TEMPERATURE_CHECK_PARAM 		= 264,

	//MONITOR 266-275
	DOMAIN_ID_MONITOR_ABILITY 				= 266,
	DOMAIN_ID_MONITOR_PARAM 				= 267,
	DOMAIN_ID_MONITOR_RESOLUTION 			= 268,
	DOMAIN_ID_MONITOR_TYPE					= 269,

	//MOTIONDETECTION 276-290
	DOMAIN_ID_MOTION_DETECTION_ABILITY 			= 276,
	DOMAIN_ID_MOTION_DETECTION_ABILITY_CONFIGURE= 277,
	DOMAIN_ID_MOTION_DETECTION_EVENT 			= 278,
	DOMAIN_ID_MOTION_DETECTION_EVENT_V2			= 279,
	DOMAIN_ID_MOTION_DETECTION_EX_ABILITY		= 280,
	DOMAIN_ID_MOTION_DETECTION_PARAM 			= 281,
	DOMAIN_ID_MOTION_DETECTION_PARAMV2			= 282,
	DOMAIN_ID_OCCLUSION_DETECTION_EVENT			= 283,
	DOMAIN_ID_OCCLUSION_DETECTION_PARAM			= 284,

	//NETWORK 291-330
	DOMAIN_ID_NETWORK_ABILITY 				= 291,
	DOMAIN_ID_NETWORK_ALARM_EVENT			= 292,
	DOMAIN_ID_NETWORK_ALARM_PARAM 			= 293,
	DOMAIN_ID_NETWORK_CARD_ABILITY			= 294,
	DOMAIN_ID_NETWORK_CARD_STATUS			= 295,
	DOMAIN_ID_NETWORK_PARAM 				= 296,
	DOMAIN_ID_BONJOUR_SERVICE_PARAM      	= 297,
	DOMAIN_ID_FTPPARAM						= 298,
	DOMAIN_ID_BROADCAST_PARAM       		= 299,
	DOMAIN_ID_HEART_BEAT_PARAM      		= 300,
	DOMAIN_ID_HOST_NETWORK      			= 301,
	DOMAIN_ID_IP_ADDR_SEGMENT      			= 302,
	DOMAIN_ID_IPC_NETWORK_ABILITY      		= 303,
	DOMAIN_ID_IPC_NETWORK_CARD_ABILITY   	= 304,
	DOMAIN_ID_IP_FILTER_PARAM     			= 305,
	DOMAIN_ID_MTU_PARAM						= 306,
	DOMAIN_ID_MULTICAST_PARAM				= 307,
	DOMAIN_ID_NTP_PARAM						= 308,
	DOMAIN_ID_NTP_PARAM_V2					= 309,
	DOMAIN_ID_PPPOE_PARAM					= 310,
	DOMAIN_ID_REGISTER_PARAM       			= 311,
	DOMAIN_ID_SECURITY_PARAM       			= 312,
	DOMAIN_ID_SERVER_PARAMETER       		= 313,
	DOMAIN_ID_SYSTEM_SERVICE_INFO       	= 314,
	DOMAIN_ID_UPNP_SERVICE_PARAM       		= 315,
	DOMAIN_ID_NET_WORKING_MODE				= 316,
	DOMAIN_ID_INET_ADDR						= 317,

	//OSD 331-350
	DOMAIN_ID_OSD_ABILITY					= 331,
	DOMAIN_ID_OSD_FONT_ABILITY				= 332,
	DOMAIN_ID_OSD_FORMAT_ABILITY 			= 333,
	DOMAIN_ID_OSD_GLOBAL_PARAM				= 334,
	DOMAIN_ID_OSD_INFO						= 335,
	DOMAIN_ID_OSD_INFO_EX 					= 336,
	DOMAIN_ID_OSD_INFO_EX_V2      			= 337,
	DOMAIN_ID_OSD_PRINT_TIME				= 338,
	DOMAIN_ID_OSD_TIME_FORMAT_TYPE      	= 339,

	//PIRALARM 351-355
	DOMAIN_ID_PIR_ALARM_ABILITY				= 351,
	DOMAIN_ID_PIR_ALARM_EVENT       		= 352,

	//PRIVILEGE 356-375
	DOMAIN_ID_PRIVILEGE 					= 366,
	DOMAIN_ID_PRIVILEGE_GROUP      			= 367,
	DOMAIN_ID_PRIVILEGE_MODULE				= 368,
	DOMAIN_ID_PRIVILEGE_USER       			= 369,
	DOMAIN_ID_SN_PRIVILEGE_USER       		= 370,

	//PROTOCOL 376-390
	DOMAIN_ID_PROTOCOL_CONFIG_ABILITY 		= 376,
	DOMAIN_ID_PROTOCOL_CONFIG_PARAM      	= 377,
	DOMAIN_ID_PROTOCOL_CONFIG_PARAM_ITEM	= 378,
	DOMAIN_ID_PROTOCOL_INFO      			= 379,
	DOMAIN_ID_PROTOCOL_SECURITY_PARAM		= 380,
	DOMAIN_ID_PROTOCOL_TYPE      			= 381,
	DOMAIN_ID_PROTOCOL_TYPE_INFO      		= 382,

	//PTZ 391-430
	DOMAIN_ID_PTZ_ABILITY     				= 391,
	DOMAIN_ID_PTZ_ABILITY_PARAM     		= 392,
	DOMAIN_ID_PTZ_KEEPER      				= 393,
	DOMAIN_ID_PTZ_KEEPER_V2   				= 394,
	DOMAIN_ID_PTZ_KEYBOARD_PARAM     		= 395,
	DOMAIN_ID_PTZ_NORTH_V2					= 396,
	DOMAIN_ID_PTZ_OPERATION_INFO			= 397,
	DOMAIN_ID_PTZ_OSD_PARAM					= 398,
	DOMAIN_ID_PTZ_PARAM						= 399,
	DOMAIN_ID_PTZ_PARAM_EX					= 400,
	DOMAIN_ID_PTZ_POINT_PARAM_V2 			= 401,
	DOMAIN_ID_PTZ_PRESET      				= 402,
	DOMAIN_ID_PTZ_PRESET_V2					= 403,
	DOMAIN_ID_PTZ_PROTOCOL      			= 404,
	DOMAIN_ID_PTZ_SCAN						= 405,
	DOMAIN_ID_PTZ_SCAN_PARAM_V2      		= 406,
	DOMAIN_ID_PTZ_SPEED      				= 407,
	DOMAIN_ID_PTZ_SPEED_PARAM_V2			= 408,
	DOMAIN_ID_PTZ_STAGE_TO_SPEED_PARAM 		= 409,
	DOMAIN_ID_PTZ_TIMER      				= 410,
	DOMAIN_ID_PTZ_TIMER_TIME_SEGMENT		= 411,
	DOMAIN_ID_PTZ_TOUR      				= 412,
	DOMAIN_ID_PTZ_TOUR_EX					= 413,
	DOMAIN_ID_PTZ_TOUR_NODE      			= 414,
	DOMAIN_ID_PTZ_TOUR_NODE_EX      		= 415,
	DOMAIN_ID_PTZ_TOUR_PARAM_V2     		= 416,
	DOMAIN_ID_PTZ_TOUR_POINT				= 417,
	DOMAIN_ID_PTZ_TOUR_POINT_V2      		= 418,
	DOMAIN_ID_PTZ_TRACE_CMD_ITEM_V1			= 419,
	DOMAIN_ID_PTZ_TRACE_V1      			= 420,
	DOMAIN_ID_PTZ_TRACK     				= 421,
	DOMAIN_ID_SCAN_ABILITY_PARAM_V2     	= 422,
	DOMAIN_ID_SCAN_REGISTERS_PARAM    		= 423,
	DOMAIN_ID_TOUR_ABILITY_PARAM_V2      	= 424,
	DOMAIN_ID_TRACE_ABILITY_PARAM_V2    	= 425,
	DOMAIN_ID_UART_PARAM    				= 426,

	//RECORD 431-465
	DOMAIN_ID_MANUAL_RECORD_PARAMETER 		= 431,
	DOMAIN_ID_MANUAL_RECORD_POLICY 			= 432,
	DOMAIN_ID_MANUAL_RECORD_STATUS 			= 433,
	DOMAIN_ID_MANUAL_SNAPSHOT_PARAMETER		= 434,
	DOMAIN_ID_NAS_STORAGE_PARAM 			= 435,
	DOMAIN_ID_RECORD_BACKUP_CONDITION		= 436,
	DOMAIN_ID_RECORD_DIR_INFO				= 437,
	DOMAIN_ID_RECORD_DIR_SPACE_INFO			= 438,
	DOMAIN_ID_RECORD_FILE 					= 439,
	DOMAIN_ID_RECORD_FILE_EX				= 440,
	DOMAIN_ID_RECORD_FILE_SEARCH_PARAM 		= 441,
	DOMAIN_ID_RECORD_BACKUP_PARAM			= 442,
	DOMAIN_ID_RECORD_INFO					= 443,
	DOMAIN_ID_RECORD_LOG_INFO				= 444,
	DOMAIN_ID_RECORD_POLICY					= 445,
	DOMAIN_ID_RECORD_QUALITY_PARAM 			= 446,
	DOMAIN_ID_RECORD_QUERY_CONDITION		= 447,
	DOMAIN_ID_RECORD_QUERY_RESULT 			= 448,
	DOMAIN_ID_RECORD_STATE					= 449,
	DOMAIN_ID_RECORD_STORAGE_PARAM			= 450,
	DOMAIN_ID_RECORD_SUMMARY_INFO			= 451,
	DOMAIN_ID_RECORD_TIME_SEGMENT			= 452,


	//ROI 466-475
	DOMAIN_ID_ROI_ABILITY 					= 466,
	DOMAIN_ID_ROI_CONFIGURE					= 467,
	DOMAIN_ID_ROI_INFO_PARAM 				= 468,

	//外部设备 476-490
	DOMAIN_ID_RS232_DEVICE_INFO				= 476,
	DOMAIN_ID_RS232_PARAM					= 477,
	DOMAIN_ID_RS485_DEVICE 					= 478,
	DOMAIN_ID_RS485_DEVICE_INFO 			= 479,
	DOMAIN_ID_CASH_REGISTERS_PARAM       	= 480,
	DOMAIN_ID_EXTERN_INTERFACE				= 481,
	DOMAIN_ID_LOUDHAILER_PARAM				= 482,
	DOMAIN_ID_TONE_ARM_PARAM				= 483,

	//SMTP 491-500
	DOMAIN_ID_SEND_MAIL_ACTION				= 491,
	DOMAIN_ID_SMTP_PARAM					= 492,
	DOMAIN_ID_SN_SMTP_PARAM					= 493,

	//SNAPSHOT 501-520
	DOMAIN_ID_SNAP_SHOT_CONFIG				= 501,
	DOMAIN_ID_SNAP_SHOT_FILE				= 502,
	DOMAIN_ID_SNAP_SHOT_PARAM 				= 503,
	DOMAIN_ID_SNAP_SHOT_PARAMETER 			= 504,
	DOMAIN_ID_SNAP_SHOT_PARAMEX      		= 505,
	DOMAIN_ID_SNAP_SHOT_POLICY				= 506,
	DOMAIN_ID_SNAP_SHOT_QUERY_CONDITION		= 507,
	DOMAIN_ID_SNAP_SHOT_SPACE_INFO			= 508,
	DOMAIN_ID_SNAP_SHOT_STATUS				= 509,
	DOMAIN_ID_SNAP_SHOT_STORAGE_PARAM 		= 510,
	DOMAIN_ID_SNAP_SHOT_TRIGGER_PARAMETER	= 511,
	DOMAIN_ID_TRAFFIC_SNAP_SHOT_POLICY		= 512,

	//STREAM 521-550
	DOMAIN_ID_STREAM_CONFIGURE				= 521,
	DOMAIN_ID_STREAM_ENCODE_ABILITY			= 522,
	DOMAIN_ID_STREAML_INFO					= 523,
	DOMAIN_ID_SUB_WIN_DECODING_ABILITY		= 524,
	DOMAIN_ID_SVC_STREAM_CONFIGURE 			= 525,
	DOMAIN_ID_SVC_STREAM_PARAM     			= 526,
	DOMAIN_ID_BITRATE_TYPE 					= 527,
	DOMAIN_ID_DECODING_ABILITY				= 528,
	DOMAIN_ID_ENCODE_QUALITY 				= 529,
	DOMAIN_ID_ENCODER_ABILITY				= 530,
	DOMAIN_ID_IMAGE_FORMAT					= 531,
	DOMAIN_ID_INTELLIGENCE_ANALYSE_ABILITY	= 532,
	DOMAIN_ID_IVA_ABILITY					= 533,
	DOMAIN_ID_MOSAIC_PARAM					= 534,
	DOMAIN_ID_REMOTE_SNAPSHOT_PARAM			= 535,
	DOMAIN_ID_RESOLUTION					= 536,
	DOMAIN_ID_SENSOR_ABILITY				= 537,
	DOMAIN_ID_SN_AV_FRAME_HEAD				= 538,
	DOMAIN_ID_SOURCE_RESOLUTION				= 539,
	DOMAIN_ID_SOURCE_RESOLUTION_ABILITY		= 540,
	DOMAIN_ID_SPECIAL_CUSTOM				= 541,

	//TIME 551-565
	DOMAIN_ID_TIME_REBOOT_PARAM				= 551,
	DOMAIN_ID_TIME_STRUCT					= 552,
	DOMAIN_ID_TIME_STRUCT_HELPER			= 553,
	DOMAIN_ID_TIME_ZONE_ABILITY				= 554,
	DOMAIN_ID_TIME_ZONE_PARAM				= 555,
	DOMAIN_ID_TIME_ZONE_TYPE				= 556,

	//USER 566-575
	DOMAIN_ID_USER    						= 566,
	DOMAIN_ID_USER_DEFINE_PARAM 			= 567,
	DOMAIN_ID_USER_DEFINE_PARAM_ITEM		= 568,
	DOMAIN_ID_USER_PARAM 					= 569,
	DOMAIN_ID_SYSTEM_USER      				= 570,
	DOMAIN_ID_SYSTEM_USER_PARAM       		= 271,

	//VIDEO 576-615
	DOMAIN_ID_VIDEO_ABILITY     			= 576,
	DOMAIN_ID_VIDEO_CAPTURE_CONFIGURE		= 577,
	DOMAIN_ID_VIDEO_CHANNEL_STATISTIC		= 578,
	DOMAIN_ID_VIDEO_DEVICE_ACCESS_PARAM		= 579,
	DOMAIN_ID_VIDEO_DISPLAY_CONFIGURE		= 580,
	DOMAIN_ID_VIDEO_ENCODE_QUALITY			= 581,
	DOMAIN_ID_VIDEO_ENCODER_ABILITY			= 582,
	DOMAIN_ID_VIDEO_EX_ABILITY				= 583,
	DOMAIN_ID_VIDEO_INFO					= 584,
	DOMAIN_ID_VIDEO_LOSE_DETECTION_EVENT	= 585,
	DOMAIN_ID_VIDEO_OSD_FONT				= 586,
	DOMAIN_ID_VIDEO_OSD_FONT_TYPE			= 587,
	DOMAIN_ID_VIDEO_OSD_INFO				= 588,
	DOMAIN_ID_VIDEO_OSD_INFO_EX				= 589,
	DOMAIN_ID_VIDEO_OUT_ABILITY				= 590,
	DOMAIN_ID_VIDEO_QUALITY					= 591,
	DOMAIN_ID_VIDEO_RESOLUTION				= 592,
	DOMAIN_ID_VIDEO_RESOLUTION_ABILITY		= 593,
	DOMAIN_ID_VIDEO_SYSTEM					= 594,
	DOMAIN_ID_VIDEO_DISPLAY_DEVICE_INFO		= 595,

	//VISS 616-620
	DOMAIN_ID_VISS_2X_PARAM     			= 616,
	DOMAIN_ID_VISS_3X_PARAM					= 617,

	//WIFI 621-630
	DOMAIN_ID_WIFI_ABILITY_PARAM			= 621,
	DOMAIN_ID_WIFI_HOTSPOT_PARAM			= 622,
	DOMAIN_ID_WIFI_NETWORK_PARAM			= 623,
	DOMAIN_ID_WIFI_PARAM					= 624,
	DOMAIN_ID_WIFI_STATE_PARAM				= 625,
	DOMAIN_ID_SN_WIFI_PARAM       			= 626,

	//WORKING 631-635
	DOMAIN_ID_WORKING_MODE					= 631,
	DOMAIN_ID_WORKING_MODE_ABILITY			= 632,

	//COLOR 636-640
	DOMAIN_ID_COLOR_PARAM       			= 636,
	DOMAIN_ID_RGB_COLOR       				= 637,

	//POLICY 641-660
	DOMAIN_ID_SAVE_POLICY					= 641,
	DOMAIN_ID_SCHEDULE_RECORD_PARAM			= 642,
	DOMAIN_ID_SCHEDULE_RECORD_POLICY		= 643,
	DOMAIN_ID_SCHEDULE_SNAPSHOT_POLICY		= 644,
	DOMAIN_ID_SCHEDULE_TIME_PARAM			= 645,
	DOMAIN_ID_SCHEDULE_TIME_SEGMENT			= 646,
	DOMAIN_ID_SN_RECORD_DIR_INFO			= 647,
	DOMAIN_ID_SPACE_POLICY					= 648,
	DOMAIN_ID_WRITE_POLICY      			= 649,
	DOMAIN_ID_BACKUP_TASK 					= 650,
	DOMAIN_ID_UPDATE_PARAM       			= 651,
	DOMAIN_ID_UPLOAD_POLICY       			= 652,
	DOMAIN_ID_SCHEDULE_TIME					= 653,
	DOMAIN_ID_SCHEDULE_WEEK					= 654,
	//OTHER 661-
	DOMAIN_ID_ZMA_PARAM      						= 661,
	DOMAIN_ID_CHAR_SET       						= 662,
	DOMAIN_ID_CPU_STATISTIC							= 663,
	DOMAIN_ID_CWMP_PARAM							= 664,
	DOMAIN_ID_DISPLAY_PARAM							= 665,
	DOMAIN_ID_LINE_CROSS       						= 666,	
	DOMAIN_ID_ALCATEL_SIP_PARAM       				= 667,
	DOMAIN_ID_MAX_OPTICAL_MAGNIFICATION_PARAM_V2    = 668,
	DOMAIN_ID_MEM_STATISTIC       					= 669,
	DOMAIN_ID_CANVAS_PROPER       					= 670,
	DOMAIN_ID_NVR_DEVICE_ABILITY       				= 671,
	DOMAIN_ID_REBOOT_TIME       					= 672,
	DOMAIN_ID_VERSION       						= 673,
	DOMAIN_ID_VIRTUAL_CHANNEL_INFO      			= 674,
	DOMAIN_ID_RESPONSE      						= 675,
	DOMAIN_ID_CHANNEL_INFO							= 676,
	DOMAIN_ID_WINDOW_MODE_INFO						= 677,
	DOMAIN_ID_WEB_SERVER_INFO						= 678,
	DOMAIN_ID_STREAM_URI_RESPONSE_INFO				= 679,
	DOMAIN_ID_CHANNEL_INFO_EX						= 680,
	DOMAIN_ID_RS485_INFO							= 681,
	DOMAIN_ID_INTER_PHONE_REQUEST_INFO				= 682,
	DOMAIN_ID_DATA_CHANNEL_REQUES_INFO				= 683,
	DOMAIN_ID_DEVICE_CONFIGURE_INFO					= 684,
	DOMAIN_ID_DECODER_REQUEST_INFO					= 685,
	DOMAIN_ID_DISK_INFO								= 686,
	DOMAIN_ID_RESPONSE_INFO							= 687,
	DOMAIN_ID_STREAM_CHANNEL_INFO					= 688,
	DOMAIN_ID_STREAM_CHANNEL_INFO_EX				= 689,
	DOMAIN_ID_VIDEO_STREAM_REQUEST_INFO				= 690,
	DOMAIN_ID_MICROPHONE_REQUEST_INFO				= 691,
	DOMAIN_ID_DEVICE_RESET_COMMAND_INFO				= 692,
	DOMAIN_ID_RECORD_STREAM_CTRL_INFO				= 693,
	DOMAIN_ID_RECORD_STREAM_RESPONSE_INFO			= 694,
	DOMAIN_ID_STRING								= 695,
	DOMAIN_ID_STREAM_URI_REQUEST_INFO				= 696,
	DOMAIN_ID_VIDEO_STREAM_RESPONSE_INFO			= 697,
	DOMAIN_ID_MULTICAST_INFO						= 698,
	DOMAIN_ID_PLAY_EXCEPTION						= 699,

    DOMAIN_ID_DOMAIN_CONTAINER                      = 9999  //todo
};






#endif  //_SN_DOMAIN_CONST_H_


